[package]
name = "libnanomite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aead = "0.5.1"
aes-gcm = "0.10.1"
bincode = "2.0.0-rc.1"
rand = "0.8.5"
rustc-hash = "1"